* Commentary
This library provides a major-mode for viewing syslog files.
You can highlight and filter the lines of the file by regular expressions and by timestamp.
* Keybindings
- "C-down" : syslog-boot-start
- "R"      : revert-buffer
- "/"      : syslog-filter-lines
- "g"      : hide-lines-show-all
- "h r"    : highlight-regexp
- "h p"    : highlight-phrase
- "h l"    : highlight-lines-matching-regexp
- "h u"    : unhighlight-regexp
- "C-/"    : syslog-filter-dates
- "D"      : open dired buffer in log directory (`syslog-log-file-directory')
- "j"      : ffap
- "<"      : syslog-previous-file
- ">"      : syslog-next-file
- "o"      : syslog-open-files
- "a"      : syslog-append-files
- "p"      : syslog-prepend-files
- "v"      : syslog-view
- "c"      : syslog-count-matches
- "k"      : hide-lines-kill-hidden
- "W"      : syslog-whois-reverse-lookup
- "!"      : syslog-shell-command
- "M-down" : syslog-move-next-file
- "M-up"   : syslog-move-previous-file
- "t"      : syslog-toggle-filenames
- "q"      : quit-window
* Commands:
Below are complete command list:

 - `syslog-shell-command' : Execute a shell COMMAND synchronously, with prefix arg (SUDOP) run under sudo. (Keybinding: !)
 - `syslog-append-files' : Append FILES into buffer BUF. (Keybinding: a)
 - `syslog-prepend-files' : Prepend FILES into buffer BUF. (Keybinding: M-x syslog-prepend-files)
 - `syslog-open-files' : Insert log FILES into new buffer. (Keybinding: o)
 - `syslog-view' : Open a view of syslog files with optional filters and highlights applied. (Keybinding: v)
 - `syslog-previous-file' : Open the previous logfile backup, or the next one if a prefix arg is used. (Keybinding: <)
 - `syslog-next-file' : Open the next logfile. (Keybinding: >)
 - `syslog-move-next-file' : Move to the next file in the current `syslog-mode' buffer. (Keybinding: <M-down>)
 - `syslog-move-previous-file' : Move to the next file in the current `syslog-mode' buffer. (Keybinding: <M-up>)
 - `syslog-toggle-filenames' : Toggle the display of filenames before each line. (Keybinding: t)
 - `syslog-filter-lines' : Restrict buffer to blocks of text between matching regexps. (Keybinding: /)
 - `syslog-filter-dates' : Restrict buffer to lines between times START and END (Emacs time lists). (Keybinding: C-/)
 - `syslog-mode' : Major mode for working with system logs. (Keybinding: M-x syslog-mode)
 - `syslog-count-matches' : Count strings which match the given pattern. (Keybinding: c)
 - `syslog-boot-start' : Jump forward in the log to when the system booted. (Keybinding: <C-down>)
 - `syslog-whois-reverse-lookup' : This is a wrapper around the `whois' command using symbol at point as default search string. (Keybinding: W)

* Customizable Options:
Below are customizable option list:

 - `syslog-mode-hook' : *Hook to setup `syslog-mode'. (default = nil)
 - `syslog-views' : A list of views. (default = nil)
 - `syslog-datetime-regexp' A regular expression matching the date-time at the beginning of each line in the log file.
 - `syslog-log-file-directory' : The directory in which log files are stored. (default = "/var/log/")

* Installation

 - If you have [[http://www.marmalade-repo.org/][marmalade-repo.org]], this syslog-mode is part of the emacs packages you can install.  Just type M-x package-install syslog-mode marmalade 
 - Otherwise download the library from here Lisp:syslog-mode, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'syslog-mode) in your ~/.emacs file

* License

=syslog-mode= is licensed under GPLv3 or later.
